### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by eyeway1968** [takielias/codeigniter4-websocket#7]
I am trying to install the library with Composer but I get the following error"[InvalidArgumentException]
  Could not find a version of package takielias/codeigniter4-websocket matching your minimum-stability (stable). Requ
  ire it with an explicit version constraint allowing its desired stability."

**Comment by takielias** [comment]
Please mention Codeigniter Version and Package version.

**Comment by eyeway1968** [comment]
Codeigniter version 4.1.1 . With "Package version" what you mean?

**Comment by takielias** [comment]
I have checked CI v 4.1.5 it works fine. Can you please explain the scenario?

**Comment by eyeway1968** [comment]
I clone your repo to a new folder on my PC, I navigate to this folder and run " composer require takielias/codeigniter4-websocket @dev" And I get the above error message.

**Comment by takielias** [comment]
Please install fresh  CI 4 and use `composer require takielias/codeigniter4-websocket @dev`

**Comment by AlexNeises** [comment]
The issue is if you're using PHP 8, despite the repo saying it works for PHP 7+, it can't be installed with PHP 8.

**Comment by alfonsotesone** [comment]
> The issue is if you're using PHP 8, despite the repo saying it works for PHP 7+, it can't be installed with PHP 8.
> 
> Here's the error I'm receiving:
> 
> ```
> [InvalidArgumentException]
> Package takielias/codeigniter4-websocket at version @dev has requirements incompatible with your PHP version, PHP extensions and Composer version:
>   - takielias/codeigniter4-websocket dev-master requires php ^7.2 which does not match your installed version 8.0.15.
> ```

Same problem here!

**Comment by takielias** [comment]
> The issue is if you're using PHP 8, despite the repo saying it works for PHP 7+, it can't be installed with PHP 8.
> 
> Here's the error I'm receiving:
> 
> ```
> [InvalidArgumentException]
> Package takielias/codeigniter4-websocket at version @dev has requirements incompatible with your PHP version, PHP extensions and Composer version:
>   - takielias/codeigniter4-websocket dev-master requires php ^7.2 which does not match your installed version 8.0.15.
> ```

Got it. Thanks for the issue. I need time to fix it for PHP 8.0. Any PR would be appreciated.

**Comment by aldiku** [comment]
I have successfully installed this websocket library on Codeigniter 4.1.9 and PHP 8.1 using : 
`composer require takielias/codeigniter4-websocket @dev --ignore-platform-req=php`

**Comment by mdestafadilah** [comment]
> I have successfully installed this websocket library on Codeigniter 4.1.9 and PHP 8.1 using : `composer require takielias/codeigniter4-websocket @dev --ignore-platform-req=php`

it's work, but when running `composer update` we must remove line this before running update.

**Comment by takielias** [comment]
I'm going to release a new version for PHP 8

**Comment by mdestafadilah** [comment]
> I'm going to release a new version for PHP 8

we waiting for it. nice to hear.
